### ISSUE TITLE
Displays two cursor at the same time when trying to search

### ISSUE THREAD

**Issue by azbshiri** [junegunn/vim-oblique#66] opened 2016-09-20 12:22 UTC
Hey, I just installed you plugin but when I try to search the cursor becomes two.

**Comment by junegunn** [comment] 2016-09-20 16:59
Duplicate of #51. This plugin has many quirks and issues that cannot be easily fixed. I suggest that you instead try simpler solutions like https://github.com/pgdouyon/vim-evanesco.

**Closed by junegunn** 2016-09-20 16:59 UTC
